# Site settings
title: Quru - Technical services
email: info@quru.com
description: Here's Quru Internal website for testing purposes. Integration between Snipcart, Jekyll, Github. We hope you like it!
baseurl: "/testing-website" # the subpath of your site, e.g. /blog/
url: "https://ninilanouille.github.io" # the base hostname & protocol for your site
twitter_username: QuruFM
github_username:  Snipcart
api_key: YjdiNWIyOTUtZTIyMy00MWMwLTkwNDUtMzI1M2M2NTgxYjE0

# Build settings
markdown: kramdown
collections:
  products:
    output: true
